global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "bookingSystem-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: "/metrics"

  - job_name: "bookingSystem-be"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:8080" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "bookingSystem-nodeExporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: "bookingSystem-mysqlExporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
    metrics_path: "/metrics"

  - job_name: "bookingSystem-redisExporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9121" ]
    metrics_path: "/metrics"
