spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      indent-output: true
  data:
    redis:
      host: 127.0.0.1 # Host of the Redis server
      port: 6319 # Port of the Redis server for connection
      password: # Password for connecting to the Redis server (default is empty)
      lettuce:
        pool: # Connection pool settings
          max-active: 8 # Maximum number of active connections in the pool (uses -1 for no limit)
          max-idle: 8 # Maximum number of idle connections in the pool
          min-idle: 0 # Minimum number of idle connections in the pool
          max-wait: -1ms # Maximum wait time to get a connection from the pool (uses -1 for no limit)
      connect-timeout: 30000 # Connection timeout (in milliseconds)
resilience4j:
  ratelimiter:
    instances:
      backendA:
        limit-for-period: 2   # max request
        limit-refresh-period: 10s # in this period before refresh
        timeout-duration: 0 # beyond limit -> reject immediately
        register-health-indicator: true
        event-consumer-buffer-size: 100
      backendB:
        limit-for-period: 6
        limit-refresh-period: 500ms
        timeout-duration: 5s

  circuitbreaker:
    instances:
      cbBackEndCheck:
              registerHealthIndicator: true
              slidingWindowSize: 10
              permittedNumberOfCallsInHalfOpenState: 3 # for open half state. allow number of request to test before close breaker
              minimumNumberOfCalls: 5 # number of request sent before judge the risk of service down
              waitDurationInOpenState: 50s
              failureRateThreshold: 50
              eventConsumerBufferSize: 10

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
